config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'auth'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "users#index"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum gender: { male: 0, female: 1, transgender: 3 }

  validates :email, 
            :uniqueness => {:message => "Another account is already using this email address"},
            :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
            :message=> "Please Check Email Id" },
            :presence =>true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :country, presence: true

  scope :filter_by_country, -> (country) { where country: country }
  scope :filter_by_age, -> (age) { where age: age }

  def self.search(params)
    users = all
    users = users.filter_by_age(params[:age]) if params[:age].present?
    users = users.filter_by_country(params[:country]) if params[:country].present?
    users = users.send(params[:gender]) if params[:gender].present?
    users
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :gender, :country, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age, :gender, :country, :email, :password, :current_password])
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_default_pagination

  def index
    @users = User.search(filtering_params).paginate(page: params[:page], per_page: params[:per_page])
  end

  private

  def filtering_params
    params.fetch(:search, {}).permit(:age, :gender, :country)
  end

  def set_default_pagination
    page = params[:page] || 1
    per_page = params[:per_page] || 10
    params.merge!({page: page, per_page: per_page})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def boostrap_class(alert)
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
      danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
        concat(content_tag(:button, id: "close-button", class: "close", type: :button, data: { dismiss: 'alert' }, "aria-label" => :Close) do
          concat content_tag(:span, "&times;".html_safe, "aria-hidden" => true)
        end)
        concat message
      end)
    end
    nil
  end

  def country_options
    Country.all.map{ |c| ["#{c.name} - #{c.alpha_3}", c.name] }
  end

  def gender_options
    [['Male', 'male'], ['Female', 'female'], ['Transgender', 'transgender']]
  end

  def date_formatter(date)
    date.to_date.strftime('%b %d %Y') rescue ''
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>ZeidlerAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :get, class: "nav-link" %>
            </li>
          <% else %>
            <% if params[:controller] != 'devise/registrations' %>
              <li class="nav-item #{(params[:controller] == 'devise/registrations')? 'active' : ''}">
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
              </li>
            <% end %>
            <% if params[:controller] != 'devise/sessions' %>
              <li class="nav-item #{(params[:controller] == 'devise/sessions')? 'active' : ''}">
                <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </nav>
      <%= yield %>
    </div>  
  </body>
</html>

app/views/users/_search_form.html.erb
<%= form_tag(users_path, :method => "get",   
    class: 'navbar-form navbar-left', style: "display: block ruby;") do %>  
  <div class="form-group col-sm-3 col-md-3 col-lg-3 mx-auto">
    <%= text_field_tag 'search[age]', '', class: "form-control", placeholder: "Enter age" %>
  </div>
  <div class="form-group col-sm-3 col-md-3 col-lg-3 mx-auto">
    <%= select_tag 'search[gender]', options_for_select(gender_options, params.try(:[], :search).try(:[], :gender)), { :include_blank => 'Gender', class: 'form-control', style: "border-radius: 0px !important; height: 34px !important;" } %>
  </div>
  <div class="form-group col-sm-3 col-md-3 col-lg-3 mx-auto">
    <%= select_tag 'search[country]', options_for_select(country_options, params.try(:[], :search).try(:[], :country)), { :include_blank => 'Country', class: 'form-control', style: "border-radius: 0px !important; height: 34px !important;" } %>
  </div>
  <div class="form-group col-sm-3 col-md-3 col-lg-3 mx-auto">
    <%= submit_tag 'Search', class: "btn btn-info" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-12 mx-auto">
    <div class="card card-signin my-5">
      <div class="card-body">
        <h5 class="card-title text-center">Users Listing</h5>
        <%= render 'search_form' %>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th class="th-sm">Name

              </th>
              <th class="th-sm">Email

              </th>
              <th class="th-sm">Gender

              </th>
              <th class="th-sm">Age

              </th>
              <th class="th-sm">Country

              </th>
              <th class="th-sm">Registered date

              </th>
            </tr>
          </thead>
          <tbody>
            <%- @users.each do |user| %>
              <tr>
                <td><%= user.full_name %></td>
                <td><%= user.email %></td>
                <td><%= user.gender %></td>
                <td><%= user.age %></td>
                <td><%= user.country %></td>
                <td><%= date_formatter(user.created_at) %></td>
              </tr>
            <% end %>
          </tbody>
          <% if @user.present? %>
            <tfoot>
              <tr>
                <th>Name
                </th>
                <th>Email
                </th>
                <th>Gender
                </th>
                <th>Age
                </th>
                <th>Country
                </th>
                <th>Registered Date
                </th>
              </tr>
            </tfoot>
            <% end %>
        </table>
        <%= will_paginate @users %>
      </div>
    </div>
  </div>
</div>